/**
 * Generated by orval v6.21.0 🍺
 * Do not edit manually.
 * Sample Post API
 * OpenAPI spec version: 1.0.0
 */

export type GetPosts200Item = {
  /** The unique identifier for the post. */
  id?: number;
  /** The title of the post. */
  title?: string;
};
