openapi: 3.0.3
info:
  title: Sample Post API
  version: 1.0.0
paths:
  /posts:
    get:
      summary: Get a list of posts
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                      description: The unique identifier for the post.
                    title:
                      type: string
                      example: "Post 1"
                      description: The title of the post.
